repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      # フォーマットチェックのみ実行する（修正はしない）
      # args: [ --check ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-toml
    - id: debug-statements
    - id: check-merge-conflict

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
    - id: mypy
      additional_dependencies: [types-requests]
      exclude: ^tests/

# ローカルフックの追加
- repo: local
  hooks:
    - id: check-formatting
      name: Check code formatting with ruff
      language: system
      entry: bash -c 'cd /Users/r-horie/private/mcp-rag && uv run ruff format --check src/rag_core src/rag_api_server src/mcp_adapter'
      types: [python]
      pass_filenames: false
