name: Lint Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Lint with Ruff
        run: |
          uvx ruff check . --output-format=github