name: Lint Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
    
      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Lint with Ruff
        run: |
          uvx ruff check . --output-format=github
